### ISSUE TITLE
World.step is buggy when attempting to account for variable framerate

### ISSUE THREAD

**Issue by codynova** [react-spring/cannon-es#16]
When passing a `timeSinceLastCalled` value to the `world.step` method, the simulation performance quickly degrades beyond usability.

[Example usage: Cannon demo](https://github.com/schteppe/cannon.js/blob/master/build/cannon.demo.js#L719)

[cannon.js issue 371](https://github.com/schteppe/cannon.js/issues/371)

[Article: Fix your timestep](https://gafferongames.com/post/fix_your_timestep/)

[Spectrum chat: World step does not adapt to framerate](https://spectrum.chat/use-cannon/general/world-step-does-not-adapt-to-frame-rate~d921bd05-bf32-494a-ad5e-2af9d99cbc5f)

Per Schteppe (schteppe#371):

>Perhaps the number of substeps are maxed out? This could happen if you, for example, pass in deltaTime in milliseconds instead of seconds... or if you accidentally calculate the value wrong for the first frame (there is no “previous” time value). or if the first deltaTime values are too large (they usually are larger during the first frames while the JIT is warming up).
What happens if you pass in 1000 substeps instead of 10? If you have implemented it correctly, changing the number of substeps should do nothing.

**Comment by Platane** [comment]
I added support for `timeSinceLastCalled` in the worker. On this fork [Platane/use-cannon](https://github.com/Platane/use-cannon/commits/master)

I updated the demo to highlight issues. The ping pong demo is particularly relevant.


![frame rate demo](https://user-images.githubusercontent.com/1659820/78649194-68c34080-78bd-11ea-8372-3706809d69f3.gif)

Well it's not easy to catch since the gif framerate is also super low. But you can notice that :
- first it runs well at 60fps, with `maxSubSteps` set to 1 which is equivalent to not using `timeSinceLastCalled`
- then I lower the framerate by running junk code at every frame. The simulation seems to slow ( but not the paddle )
- when I increase `maxSubSteps` it runs more that one internal step at each frame in order to match the actual time elapsed rather than be dependent on frame rate.

You can try it here [demo/Pingpong](https://cannon-framerate-demo-48mxcy534.now.sh/#/demo/Pingpong)

So far I did not encounter wacky simulation explosions as referenced in https://github.com/schteppe/cannon.js/issues/371


---

There one thing I find odd in the implementation. If maxSubStep is not sufficient to catch up with the actual time, the accumulator build up seconds of delay. So when the framerate gets better, to lower the accumulator the simulation will actually run faster for a few seconds !


![frame rate demo](https://user-images.githubusercontent.com/1659820/78650287-023f2200-78bf-11ea-8856-88f09c4a06da.gif)

here you can see in the log that the maxsubstep is not sufficient, so it fills up the accumulator.
Once i release the pressure on the frame rate, the simulation speed up (again hard to see in the gif :x ) until the accumulator is emptied.

One strategy that I rather have would be to prevent the accumulator to build up more than X dt delay.

**Comment by codynova** [comment]
I'm seeing the same issue here that I was seeing in my own local attempt at implementing `timeSinceLastCalled`, and mentioned in the issue on Schteppe's github

Leave the wasted frames set to 0, and leave `maxSupSteps` at 1. Watch the falling instanced cubes demo. The framerate looks good, but switching between browser tabs causes some of the cubes to freeze in midair until they despawn. This doesn't seem to happen on the current `use-cannon@0.4.2`.

Leave the wasted frames set to 0, and turn `maxSupSteps` to 7. Watch the falling instanced cubes demo again, the framerate degrades heavily.

**Comment by Platane** [comment]
the tab switching makes sense, since request animation frame gets paused, the delta when focusing back is huge.

---

About the cube heap, it pretty interesting, it looks like the simulation takes too long to be renderer at live speed. It takes more than `dt` to compute `step(dt)` which builds up a delay that need to be catch up (the `accumulator` prop). Eventually filling all the `maxSubSteps` available.

In that case it is indeed a better solution to slow down the simulation, giving up on rendering at live speed.

One obvious fix could be to prevent the accumulator to grow out of control, as I don't see any situation where it leads to expected behaviour.

We could also detect slow rendering simulation and shortcut them for the sake of keeping a good framerate at the cost of slowing down the simulation.

**Comment by marcofugaro** [comment]
[Is this PR](https://github.com/schteppe/cannon.js/pull/392) somehow related? I think we should bring in that PR as well.

**Comment by Platane** [comment]
yes it seems so, although it also brings questionable features ( "timeSinceLastCalled = -1 instead of 0" )

I am not sure this address the cube freezing midair effect, I am looking into that.

**Comment by marcofugaro** [comment]
You're right, `timeSinceLastCalled === -1` is weird, I would personally just check if the argument was passed as 0 or wasn't passed at all

```js
if (timeSinceLastCalled === undefined) {
```

and stop. Get rid of the `timeSinceLastCalled = 0;` and update its type to optional number

Can you do that in your existing PR? Or should we do a different PR?

**Comment by Platane** [comment]
@marcofugaro agreed

tbh I rather have two methods. How about renaming internalStep step, and allowing it to be called publicly, and renaming the actual step something like `executeSteps` and enforcing the 3 params existance.

**Comment by marcofugaro** [comment]
That's a big api change 😬maybe if this library was a standalone physics library instead of a fork of cannon, we could have done it.

The only valid api changes I see are the ones to modernize the library and the ones that make it more compatible with Three.js

**Comment by Platane** [comment]
Yes You are right. I was thinking loudly :)

**Comment by codynova** [comment]
This looks good and is working well now except for the freezing cubes (no framerate degradation in my testing). We should wait to merge until that issue is resolved.

I agree with Marco regarding API changes, we should strive to make as few API changes as possible, and maintain backwards compatibility where we can.

@Platane Great work on this so far, I think supporting variable framerate would be a huge feature.

**Comment by codynova** [comment]
@Platane I spoke too soon in my last comment, framerate is still degrading heavily over time on the latest of your fork with `maxSubSteps` set to 7.

I wonder if this commit might give us some insight into how the accumulator was expected to be used, and why `this.time` was incremented in both the `step` and `internalStep` https://github.com/schteppe/cannon.js/commit/e42557ab01aa1e62713f0b7f3d7e052f7405dd87

**Comment by Platane** [comment]
ok I will check. What environment are you using ? I can't reproduce the frame rate drop on chrome desktop :/

**Comment by codynova** [comment]
I'm using Google Chrome Version 81.0.4044.92 (Official Build) (64-bit), on Windows 10 x64, on an extremely powerful desktop (Intel i7-8700K@3.7, Nvidia 1080TI). I can test with a Mac on Chrome and Safari later today.

I just set the `maxSubSteps` to 7 and leave it running for 5 - 10 minutes or so. I can time how long it takes to degrade and maybe record a video later today if that will help.

**Comment by codynova** [comment]
@Platane I may have made some mistake in my testing. I set everything up from scratch and stuff is looking much better.

I don't think I'm able to reproduce the cubes freezing in midair anymore, are you?

It also looks like the framerate degradation may be completely gone, although I want to leave this running for longer before I say for sure. However, when setting `maxSubSteps` to anything other than the default 1, the simulation seems to speed up significantly. That's not expected, correct?

**Comment by Platane** [comment]
Ok good, that seems consistent with what I experienced so far.

The simulation might appear sped up when increasing the maxSubStep if one step was not sufficient to render at live speed.

I am focusing on the freezing cube issue. I don't see it as often as before, but still more than never (which is the case in the current stable version)

**Comment by codynova** [comment]
Would you expect that the simulation stays sped up consistently? It seems like it should catch up at some point, but that doesn't seem to be the case while testing the cube heap demo.

**Comment by Platane** [comment]
I think the sped up version is the actual speed. It was previously slower because we restricted to one step (1/60s of simulation ) each animation frame ( > 1/60s of real time ).

**Comment by codynova** [comment]
But wouldn't it only be slower if it wasn't achieving 60fps? I thought the whole point of variable framerate stepping is to achieve the same simulation speed between high-performance 60fps code and low-performance variable framerate code?

**Comment by Platane** [comment]
yes that's the goal. Unless something goes wrong in the current version (which is probable), it should do exacty that.

**Comment by codynova** [comment]
Released fix in `cannon-es@0.15.0`
