### ISSUE TITLE
ConvexPolyhedron() has empty vertices and faces arrays when created, and has a vsub error

### ISSUE THREAD

**Issue by kylewetton** [react-spring/cannon-es#17]
Once passing a Geometry with verticies and faces to ConvexPolyhedron, the arrays of both get stripped, this breaks the ability to use the ConvexPolyhedron. Another issue is that ConvexGeometry strips the bounding shapes (both box and sphere), not sure if this is causing the error 
`TypeError: Cannot read property 'vsub' of undefined
    at Function.ConvexPolyhedron.computeNormal` 

An example is here
https://codesandbox.io/s/convexpolyhedron-test-pjwrr?runonclick=1&file=/src/index.js

To see the issue, toggle the bool on line 58

**Comment by kylewetton** [comment]
To expand on this
I'm having more luck with this
`let vec3s = cg.vertices.map((v) => new Vec3(v.x, v.y, v.z));
    let poly = new ConvexPolyhedron({ vertices: vec3s, faces: cg.faces });`

Because Cannon expects vertices to be **Vec3s** where vsub exists as a method.

BUT, faces come from ConvexGeometry as a **Face3** class, not an array

It's finally breaking down in **getFaceNormal** because va, vb, and vc assume that the Face3 is an array, instead of looking for **a**, **b** and **c**.

`    const f = this.faces[i];
    const va = this.vertices[f[0]]; 
    const vb = this.vertices[f[1]];
    const vc = this.vertices[f[2]];
`
eg. If I _console.log(f)_, I get this:

``Face3
a: 0
b: 1
c: 2
normal: Vector3 {x: -0.16077024640778023, y: 0, z: -0.9869918580565807}
vertexNormals: (3) [Vector3, Vector3, Vector3]
color: Color {}
vertexColors: []
materialIndex: 0`

So _f[0], f[1], _and_ f[2]_ are not going to work here.

**Comment by kylewetton** [comment]
Update: I've fixed this

I did this check

```
let f = this.faces[i];
f = f instanceof THREE.Face3 ? [f.a, f.b, f.c] : f;
```
Inside computeEdges(), computeNormals(), and getFaceNormal()

**Comment by codynova** [comment]
@kylewetton Thanks very much for the detailed bug report. I'm sorry for the delayed response.

Could we do something like this in the `ConvexPolyhedron` constructor?

```js
this.faces = faces[0] instanceof Array ? faces : faces.map(({ a, b, c }) => ([ a, b, c ]))
```

**Comment by stockHuman** [comment]
Hey @kylewetton, just to be absolutely sure: you're familiar with use-cannon, right? Your solution looks like an independent discovery / implementation of [use-cannon's hooks](https://github.com/react-spring/use-cannon/blob/master/src/hooks.ts#L335).

@codynova Why is this a bug? ConvexPolyhedron's constructor doesn't take THREE.Geometry or it's raw data. I must be missing something here.

**Comment by codynova** [comment]
@stockHuman Nope, I'm the one that was missing something, you are correct.

**Comment by kyleatblackfoot** [comment]
@codynova @stockHuman 

I did check use-cannon to see why ConvexPolyhedron worked for an imported GLTF model, where cannon-es fails. I understand that ConvexPolyhedron doesn't take THREE.Geometry or its raw data.

It's dawning on me though that shaping the _face_ array can be done before creating the new ConvexPolyherdron and doesn't have to be done within cannon-es script itself. The reason I initially overlooked this is because use-cannon does this check, whereas cannon-es does not. 

So to confirm, ConvexPolyhedron is expecting Vec3 for vertices and and all Face3s converted a multidimensional array.

I do propose in a feature request in that case, that perhaps in those four methods, that there is a conditional check to make it easier for the end user to directly use a THREE.Geometry  directly by doing these checks inside the script base, how worthwhile that is, perhaps not very much so. Worth the thought though.

**Comment by arpu** [comment]
@kyleatblackfoot  do oyu have some infos how i can get your codesandbox example work with ConvexPolyhedron?

**Comment by kylewetton** [comment]
@arpu sure thing, I've updated the codesandbox to show it working, 

https://codesandbox.io/s/convexpolyhedron-test-pjwrr

Lines 28 - 46 cover all of it

**Comment by arpu** [comment]
wau @kyleatblackfoot  thx a lot this helps a lot! 
one other question its not related to this issue but do you get Trimmesh Cannon working?

**Comment by arpu** [comment]
trying with Trimesh https://codesandbox.io/s/convexpolyhedron-test-ixvb0?file=/src/index.js  but so far no success

**Comment by arpu** [comment]
ok looks like  this is working with BufferGeometry

@kyleatblackfoot  https://codesandbox.io/s/trimesh-test-ixvb0
