### ISSUE TITLE
Collision between box and convex does not work properly

### ISSUE THREAD

**Issue by OliverXH** [react-spring/cannon-es#43]
After adding a convex collision body to the imported model, the test found that the collision between box and convex did not work properly

Demo is [here](https://oliverxh.github.io/demo/index.html)

You can change the shape of the red object used for the test.

**Comment by swift502** [comment]
Can confirm this is a big issue in Cannon.
@robrohan tackled this in [Dapao](https://github.com/TheRohans/dapao), however apparently unsuccessfully.

The supplied demo seems to be running Cannon, so we can port to cannon-es to see if the issue persists. I'm not sure if there were significant changes made to Convex v Convex narrowphase in cannon-es so far that would solve this.

If this problem is resolved, I will definitely switch cannon-es myself. 👍

**Comment by codynova** [comment]
Hi @OliverXH, as @swift502 mentioned, your demo is running `cannon` (cannon.js) and not `cannon-es`. I believe the collision issues should be resolved in this lib. I'm closing this for now, but if you find bugs with `cannon-es` please feel free to open an issue - or ping me here if this should be reopened.

**Comment by swift502** [comment]
I tried porting the demo but I can't get the collisions to work at all. The ramp just falls through the floor.

**Comment by codynova** [comment]
There are a couple API updates in `cannon-es` that are mentioned in the readme. For ConvexPolyhedron, the constructor API has been standardized to take an options object as the argument. You can check out the constructor in the source code, it supports pretty much all the same options as Cannon.js.

**Comment by marcofugaro** [comment]
The convex body collisions still look fine in cannon-es:

https://raw.githack.com/react-spring/cannon-es/examples-update/examples/stacks.html

The demo you provided has too much stuff going on to be able to debug. If you can provide a minimal example like the example I posted, running cannon-es, and with the issue happening, we might consider looking at it.
