### ISSUE TITLE
Moving body forward according to its quaternion

### ISSUE THREAD

**Issue by kevincastejon** [react-spring/cannon-es#44]
I got a sphere body with a changing quaternion, I just want that body to move forward according to its quaternion. I found many topics related to that but none of the suggested codes is working. 
Is it a simple way to achieve that simple task?

**Comment by marcofugaro** [comment]
You need to apply a force or velocity in the direction of the quaternion. To get the direction vector, you take a unit vector and call [applyQuaternion](https://threejs.org/docs/index.html#api/en/math/Vector3.applyQuaternion) passing the desired quaternion.
That method is not currently in the cannon vector class, but we plan to support it in the future. In the meantime you can take the code from the three.js source.

Closing this since it's an help request, please use stackoverflow next time.

**Comment by kevincastejon** [comment]
thanks for your answer, I did ask on SO but got no attention at all,  so me using pure cannonjs (no render) means that I cannot move a body forward?

**Comment by marcofugaro** [comment]
No man, you can use this code

https://github.com/mrdoob/three.js/blob/b5c272cf408cb33153190fa715d81581bd95ee47/src/math/Vector3.js#L289-L309
